-- AlterTable hotspots
ALTER TABLE `hotspots`
ADD COLUMN `animationType` ENUM('NONE', 'PULSE', 'GLOW', 'BOUNCE', 'FLOAT') NOT NULL DEFAULT 'NONE',
ADD COLUMN `iconUrl` TEXT NULL,
ADD COLUMN `iconName` VARCHAR(191) NULL DEFAULT 'info',
ADD COLUMN `color` VARCHAR(7) NULL,
ADD COLUMN `scale` DOUBLE NOT NULL DEFAULT 1.0;
